server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/customer
    username: ivanboyukliev
  jpa:
    hibernate:
      ddl-auto: create-drop  #always have empty tables when starting the app (not recommended in prod)

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411 #! zipkin in this url is the name of the zipkin container
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka #! eureka-server in this url is the name of the eureka-server container
    fetch-registry: true
    register-with-eureka: true
