server:
  port: 8083

spring:
  application:
    name: api-gateway
  zipkin: # zipkin is used for visualization of request's trance in microservices architecture
    base-url: http://zipkin:9411 #! zipkin in this url is the name of the zipkin container
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka # eureka-server in this name is actually the eureka-server container
    fetch-registry: true
    register-with-eureka: true
