server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/fraud
    username: ivanboyukliev
  jpa:
    hibernate:
      ddl-auto: create-drop #always have empty tables when starting the app (not recommended in prod)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
